# Generated by Django 5.1.5 on 2025-01-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_studentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='StudentAddress',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='StudentEmail',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='StudentName',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
